tag: browser
title: /diagrams.net/
-
line break: user.fire_chicken_diagrams_os_normalized_keypress('enter')
indent: user.fire_chicken_diagrams_os_normalized_keypress('tab')
edit cell label: user.fire_chicken_diagrams_os_normalized_keypress('f2')
stop editing: user.fire_chicken_diagrams_os_normalized_keypress('esc')
bold: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-b')
italic: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-i')
underline: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-u')
superscript: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-.')
subscript: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-,')
copy: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-c')
cut: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-x')
paste: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-v')
group: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-g')
ungroup: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-u')
lock: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-l')
unlock: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-l')
edit link: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-l')
duplicate: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-d')
delete: user.fire_chicken_diagrams_os_normalized_keypress('delete')
delete with connections: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-delete')
delete label: user.fire_chicken_diagrams_os_normalized_keypress('shift-delete')
rotate: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-r')
exit group: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-home')
enter group: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-end')
bring to front: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-f')
send to back: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-b')
find: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-f')
clear waypoints: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-c')
edit tool tip: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-t')
autosize: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-y')
select next: user.fire_chicken_diagrams_os_normalized_keypress('tab')
select previous: user.fire_chicken_diagrams_os_normalized_keypress('shift-tab')
select all: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-a')
select vertices: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-i')
select edges: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-e')
refresh: user.fire_chicken_diagrams_os_normalized_keypress('end')
full page: user.fire_chicken_diagrams_os_normalized_keypress('enter')
home: user.fire_chicken_diagrams_os_normalized_keypress('home')
fit window: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-h')
fit page: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-j')
custom zoom: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-0')
zoom in: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-keypad_plus')
zoom out: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-keypad_minus')
layers window: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-l')
outline window: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-o')
edit metadata: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-m')
format panel: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-p')
edit vertex geometry: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-m')
tags window: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-k')
save: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-s')
save as: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-s')
undo: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-z')
connection arrows: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-a')
grid: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-g')
print: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-p')
redo: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-y')
add text: user.fire_chicken_diagrams_os_normalized_keypress('a')
add note: user.fire_chicken_diagrams_os_normalized_keypress('s')
add rectangle: user.fire_chicken_diagrams_os_normalized_keypress('d')
add ellipse: user.fire_chicken_diagrams_os_normalized_keypress('f')
freehand mode: user.fire_chicken_diagrams_os_normalized_keypress('x')
previous page: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-pageup')
next page: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-pagedown')
clear default style: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-r')
edit style: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-e')
set as default style: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-d')
copy style: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-c')
paste style: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-shift-v')
copy size: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-x')
paste size: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-v')
copy data: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-b')
paste data: user.fire_chicken_diagrams_os_normalized_keypress('alt-shift-e')
scroll down: user.mouse_scroll_down(4)
scroll up: user.mouse_scroll_up(4)
scroll right:
    user.fire_chicken_diagrams_os_normalized_keypress('shift:down')
    user.mouse_scroll_down(4)
    user.fire_chicken_diagrams_os_normalized_keypress('shift:up')
scroll left:
    user.fire_chicken_diagrams_os_normalized_keypress('shift:down')
    user.mouse_scroll_up(4)
    user.fire_chicken_diagrams_os_normalized_keypress('shift:up')
select: mouse_click(0)
Collapse container: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-home')
Expand container: user.fire_chicken_diagrams_os_normalized_keypress('ctrl-end')
shape replace:
    user.fire_chicken_diagrams_os_normalized_keypress('shift:down')
    mouse_click(0)
    user.fire_chicken_diagrams_os_normalized_keypress('shift:up')
shape down:
    user.fire_chicken_diagrams_os_normalized_keypress('alt:down')
    mouse_click(0)
    user.fire_chicken_diagrams_os_normalized_keypress('alt:up')
shape right:
    user.fire_chicken_diagrams_os_normalized_keypress('alt:down')
    user.fire_chicken_diagrams_os_normalized_keypress('shift:down')
    mouse_click(0)
    user.fire_chicken_diagrams_os_normalized_keypress('alt:up')
    user.fire_chicken_diagrams_os_normalized_keypress('shift:up')
shape up:
    user.fire_chicken_diagrams_os_normalized_keypress('alt:down')
    user.fire_chicken_diagrams_os_normalized_keypress('ctrl:down')
    mouse_click(0)
    user.fire_chicken_diagrams_os_normalized_keypress('alt:up')
    user.fire_chicken_diagrams_os_normalized_keypress('ctrl:up')
shape left:
    user.fire_chicken_diagrams_os_normalized_keypress('alt:down')
    user.fire_chicken_diagrams_os_normalized_keypress('shift:down')
    user.fire_chicken_diagrams_os_normalized_keypress('ctrl:down')
    mouse_click(0)
    user.fire_chicken_diagrams_os_normalized_keypress('alt:up')
    user.fire_chicken_diagrams_os_normalized_keypress('shift:up')
    user.fire_chicken_diagrams_os_normalized_keypress('ctrl:up')
